module Buckwalter where

romanization :: Char -> Char
romanization 'ء' = '\''
romanization 'آ' = '|'
romanization 'أ' = '>'
romanization 'ؤ' = '&'
romanization 'إ' = '<'
romanization 'ئ' = '}'
romanization 'ا' = 'A'
romanization 'ب' = 'b'
romanization 'ة' = 'p'
romanization 'ت' = 't'
romanization 'ث' = 'v'
romanization 'ج' = 'j'
romanization 'ح' = 'H'
romanization 'خ' = 'x'
romanization 'د' = 'd'
romanization 'ذ' = '*'
romanization 'ر' = 'r'
romanization 'ز' = 'z'
romanization 'س' = 's'
romanization 'ش' = '$'
romanization 'ص' = 'S'
romanization 'ض' = 'D'
romanization 'ط' = 'T'
romanization 'ظ' = 'Z'
romanization 'ع' = 'E'
romanization 'غ' = 'g'
romanization 'ـ' = '_'
romanization 'ف' = 'f'
romanization 'ق' = 'q'
romanization 'ك' = 'k'
romanization 'ل' = 'l'
romanization 'م' = 'm'
romanization 'ن' = 'n'
romanization 'ه' = 'h'
romanization 'و' = 'w'
romanization 'ى' = 'Y'
romanization 'ي' = 'y'
romanization 'ً'  = 'F'
romanization 'ٌ'  = 'N'
romanization 'ٍ'  = 'K'
romanization 'َ'  = 'a'
romanization 'ُ'  = 'u'
romanization 'ِ'  = 'i'
romanization 'ّ'  = '~'
romanization 'ْ'  = 'o'
romanization 'ٰ'  = '`'
romanization 'ٱ' = '{'
romanization 'پ' = 'P'
romanization 'چ' = 'J'
romanization 'ڤ' = 'V'
romanization 'گ' = 'G'

-- The following are not defined in the Buckwalter transliteration system
-- but are needed in practice
romanization '؟' = '?'
romanization  x = x



deromanization :: Char -> Char
deromanization '\'' =  'ء'
deromanization '|'  =  'آ'
deromanization '>'  =  'أ'
deromanization '&'  =  'ؤ'
deromanization '<'  =  'إ'
deromanization '}'  =  'ئ'
deromanization 'A'  =  'ا'
deromanization 'b'  =  'ب'
deromanization 'p'  =  'ة'
deromanization 't'  =  'ت'
deromanization 'v'  =  'ث'
deromanization 'j'  =  'ج'
deromanization 'H'  =  'ح'
deromanization 'x'  =  'خ'
deromanization 'd'  =  'د'
deromanization '*'  =  'ذ'
deromanization 'r'  =  'ر'
deromanization 'z'  =  'ز'
deromanization 's'  =  'س'
deromanization '$'  =  'ش'
deromanization 'S'  =  'ص'
deromanization 'D'  =  'ض'
deromanization 'T'  =  'ط'
deromanization 'Z'  =  'ظ'
deromanization 'E'  =  'ع'
deromanization 'g'  =  'غ'
deromanization '_'  =  'ـ'
deromanization 'f'  =  'ف'
deromanization 'q'  =  'ق'
deromanization 'k'  =  'ك'
deromanization 'l'  =  'ل'
deromanization 'm'  =  'م'
deromanization 'n'  =  'ن'
deromanization 'h'  =  'ه'
deromanization 'w'  =  'و'
deromanization 'Y'  =  'ى'
deromanization 'y'  =  'ي'
deromanization 'F'  =  'ً'
deromanization 'N'  =  'ٌ'
deromanization 'K'  =  'ٍ'
deromanization 'a'  =  'َ'
deromanization 'u'  =  'ُ'
deromanization 'i'  =  'ِ'
deromanization '~'  =  'ّ'
deromanization 'o'  =  'ْ'
deromanization '`'  =  'ٰ'
deromanization '{'  =  'ٱ'
deromanization 'P'  =  'پ'
deromanization 'J'  =  'چ'
deromanization 'V'  =  'ڤ'
deromanization 'G'  =  'گ'

-- The following are not defined in Buckwalter transliteration
-- but are needed in practice.
deromanization '?'  =  '؟'
deromanization  x   =   x
